export const GET_DEPARTMENT_STORES = "GET_DEPARTMENT_STORES";
export const EDIT_DEPARTMENT_STORE_SUCCESS = "EDIT_DEPARTMENT_STORE_SUCCESS";
export const EDIT_DEPARTMENT_STORE_ERROR = "EDIT_DEPARTMENT_STORE_ERROR";
export const CREATE_DEPARTMENT_STORE_SUCCESS = "CREATE_DEPARTMENT_STORE_SUCCESS";
export const CREATE_DEPARTMENT_STORE_ERROR = "CREATE_DEPARTMENT_STORE_ERROR";
export const DELETE_DEPARTMENT_STORE_SUCCESS = "DELETE_DEPARTMENT_STORE_SUCCESS";
export const DELETE_DEPARTMENT_STORE_ERROR = "DELETE_DEPARTMENT_STORE_ERROR";